[colors]
ansi = [
  "#48483e",
  "#dc2566",
  "#8fc029",
  "#d4c96e",
  "#55bcce",
  "#9358fe",
  "#56b7a5",
  "#acada1",
]
background = "#272822"
brights = [
  "#76715e",
  "#fa2772",
  "#a7e22e",
  "#e7db75",
  "#66d9ee",
  "#ae82ff",
  "#66efd5",
  "#cfd0c2",
]
cursor_bg = "#76715e"
cursor_border = "#76715e"
cursor_fg = "#272822"
foreground = "#f1ebeb"
selection_bg = "#cfd0c2"
selection_fg = "#48483e"
