_: {
  perSystem =
    { pkgs, ... }:
    {
      packages.platformio-core = pkgs.platformio-core.overrideAttrs (
        _: _: {
          disabledTestPaths = [
            "tests/commands/pkg/test_install.py"
            "tests/commands/pkg/test_list.py"
            "tests/commands/pkg/test_outdated.py"
            "tests/commands/pkg/test_search.py"
            "tests/commands/pkg/test_show.py"
            "tests/commands/pkg/test_uninstall.py"
            "tests/commands/pkg/test_update.py"
            "tests/commands/test_boards.py"
            "tests/commands/test_check.py"
            "tests/commands/test_platform.py"
            "tests/commands/test_run.py"
            "tests/commands/test_test.py"
            "tests/misc/test_maintenance.py"

            # requires internet connection
            "tests/misc/ino2cpp/test_ino2cpp.py"

            "tests/commands/pkg/test_exec.py::test_pkg_specified"
            "tests/commands/pkg/test_exec.py::test_unrecognized_options"
            "tests/commands/test_ci.py::test_ci_boards"
            "tests/commands/test_ci.py::test_ci_build_dir"
            "tests/commands/test_ci.py::test_ci_keep_build_dir"
            "tests/commands/test_ci.py::test_ci_lib_and_board"
            "tests/commands/test_ci.py::test_ci_project_conf"
            "tests/commands/test_init.py::test_init_custom_framework"
            "tests/commands/test_init.py::test_init_duplicated_boards"
            "tests/commands/test_init.py::test_init_enable_auto_uploading"
            "tests/commands/test_init.py::test_init_ide_atom"
            "tests/commands/test_init.py::test_init_ide_clion"
            "tests/commands/test_init.py::test_init_ide_eclipse"
            "tests/commands/test_init.py::test_init_ide_vscode"
            "tests/commands/test_init.py::test_init_incorrect_board"
            "tests/commands/test_init.py::test_init_special_board"
            "tests/commands/test_lib.py::test_global_install_archive"
            "tests/commands/test_lib.py::test_global_install_registry"
            "tests/commands/test_lib.py::test_global_install_repository"
            "tests/commands/test_lib.py::test_global_lib_list"
            "tests/commands/test_lib.py::test_global_lib_uninstall"
            "tests/commands/test_lib.py::test_global_lib_update"
            "tests/commands/test_lib.py::test_global_lib_update_check"
            "tests/commands/test_lib.py::test_install_duplicates"
            "tests/commands/test_lib.py::test_lib_show"
            "tests/commands/test_lib.py::test_lib_stats"
            "tests/commands/test_lib.py::test_saving_deps"
            "tests/commands/test_lib.py::test_search"
            "tests/commands/test_lib.py::test_update"
            "tests/commands/test_lib_complex.py::test_global_install_archive"
            "tests/commands/test_lib_complex.py::test_global_install_registry"
            "tests/commands/test_lib_complex.py::test_global_install_repository"
            "tests/commands/test_lib_complex.py::test_global_lib_list"
            "tests/commands/test_lib_complex.py::test_global_lib_uninstall"
            "tests/commands/test_lib_complex.py::test_global_lib_update"
            "tests/commands/test_lib_complex.py::test_global_lib_update_check"
            "tests/commands/test_lib_complex.py::test_install_duplicates"
            "tests/commands/test_lib_complex.py::test_lib_show"
            "tests/commands/test_lib_complex.py::test_lib_stats"
            "tests/commands/test_lib_complex.py::test_search"
            "tests/package/test_manager.py::test_download"
            "tests/package/test_manager.py::test_install_force"
            "tests/package/test_manager.py::test_install_from_registry"
            "tests/package/test_manager.py::test_install_lib_depndencies"
            "tests/package/test_manager.py::test_registry"
            "tests/package/test_manager.py::test_uninstall"
            "tests/package/test_manager.py::test_update_with_metadata"
            "tests/package/test_manager.py::test_update_without_metadata"
            "tests/test_builder.py::test_build_flags"
            "tests/test_builder.py::test_build_unflags"
            "tests/test_builder.py::test_debug_custom_build_flags"
            "tests/test_builder.py::test_debug_default_build_flags"
            "tests/test_misc.py::test_api_cache"
            "tests/test_misc.py::test_ping_internet_ips"
            "tests/test_misc.py::test_platformio_cli"
            "tests/test_pkgmanifest.py::test_packages"
          ];
        }
      );
    };
}
