# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gh-q = {
    pname = "gh-q";
    version = "5dc627f350902e0166016a9dd1f9479c75e3f392";
    src = fetchurl {
      url = "https://github.com/kawarimidoll/gh-q/raw/main/gh-q";
      sha256 = "sha256-i6EYYRrzC+9LzsGsA0fekMQIZAth1oEWd1L8+tkbmTA=";
    };
    date = "2021-11-20";
  };
  tokyo-night-yazi = {
    pname = "tokyo-night-yazi";
    version = "caa00abcce9886373d687d8aea8b812870f74da7";
    src = fetchFromGitHub {
      owner = "BennyOe";
      repo = "tokyo-night.yazi";
      rev = "caa00abcce9886373d687d8aea8b812870f74da7";
      fetchSubmodules = false;
      sha256 = "sha256-MRlvOVW7o9M/bPUDZbajjUA2nUtcIm8S1CJZLgMHYjI=";
    };
    date = "2024-12-30";
  };
}
