# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gh-q = {
    pname = "gh-q";
    version = "a312c67b92baefadb07481ef1479c96d91243d41";
    src = fetchurl {
      url = "https://github.com/kawarimidoll/gh-q/raw/main/gh-q";
      sha256 = "sha256-mjad7EUgDC0efY+TNjTtoueO83CVkQ/sCejfD++xZYQ=";
    };
    date = "2025-03-20";
  };
  tokyo-night-yazi = {
    pname = "tokyo-night-yazi";
    version = "695dac6bcc605ba4b0bf1b1f56169eaa7cc4bb40";
    src = fetchFromGitHub {
      owner = "BennyOe";
      repo = "tokyo-night.yazi";
      rev = "695dac6bcc605ba4b0bf1b1f56169eaa7cc4bb40";
      fetchSubmodules = false;
      sha256 = "sha256-+wZzxLPCttJ2WoDdI89sQ+CcZSFIA44HshxMoh4rJIs=";
    };
    date = "2025-03-02";
  };
}
