# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gh-q = {
    pname = "gh-q";
    version = "a312c67b92baefadb07481ef1479c96d91243d41";
    src = fetchurl {
      url = "https://github.com/kawarimidoll/gh-q/raw/main/gh-q";
      sha256 = "sha256-mjad7EUgDC0efY+TNjTtoueO83CVkQ/sCejfD++xZYQ=";
    };
    date = "2025-03-20";
  };
  tokyo-night-yazi = {
    pname = "tokyo-night-yazi";
    version = "b3950bf0f51f13ab5e22b61267298554d798c63b";
    src = fetchFromGitHub {
      owner = "BennyOe";
      repo = "tokyo-night.yazi";
      rev = "b3950bf0f51f13ab5e22b61267298554d798c63b";
      fetchSubmodules = false;
      sha256 = "sha256-WtOjzk7ATA4Ue6Lu6IgiweOIHk/BK01Khio6ESF201k=";
    };
    date = "2025-05-05";
  };
}
