local options = {
    autoread     = true,
    backspace    = 'eol,indent,start',
    backup       = false,
    clipboard    = 'unnamedplus',
    compatible   = false,
    cursorcolumn = true,
    cursorline   = true,
    enc          = 'utf-8',
    expandtab    = true,
    fenc         = 'utf-8',
    fencs        = 'utf-8,cp932,sjis,iso-2022-jp,euc-jp',
    ff           = 'unix',
    hidden       = true,
    hlsearch     = true,
    ignorecase   = true,
    incsearch    = true,
    laststatus   = 2,
    listchars    = 'eol:$,tab:>-',
    modeline     = true,
    modelines    = 5,
    modifiable   = true,
    number       = true,
    shiftwidth   = 4,
    showcmd      = true,
    signcolumn   = 'yes',
    smartcase    = true,
    smartindent  = true,
    swapfile     = false,
    tabstop      = 4,
    timeout      = true,
    timeoutlen   = 1000,
    ttimeoutlen  = 1000,
    updatetime   = 1000,
    virtualedit  = 'onemore',
    wildmode     = 'list:longest',
    wrapscan     = true,
    writebackup  = false
}

for k, v in pairs(options) do
    vim.opt[k] = v
end
