[colors]
ansi = [
  "#15161e",
  "#f7768e",
  "#9ece6a",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#a9b1d6",
]
background = "#1a1b26"
brights = [
  "#414868",
  "#ff899d",
  "#9fe044",
  "#faba4a",
  "#8db0ff",
  "#c7a9ff",
  "#a4daff",
  "#c0caf5",
]
compose_cursor = "#ff9e64"
cursor_bg = "#c0caf5"
cursor_border = "#c0caf5"
cursor_fg = "#1a1b26"
foreground = "#c0caf5"
scrollbar_thumb = "#292e42"
selection_bg = "#283457"
selection_fg = "#c0caf5"
split = "#7aa2f7"

[colors.tab_bar]
background = "#1a1b26"
inactive_tab_edge = "#16161e"

[colors.tab_bar.active_tab]
bg_color = "#7aa2f7"
fg_color = "#16161e"

[colors.tab_bar.inactive_tab]
bg_color = "#292e42"
fg_color = "#545c7e"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#292e42"
fg_color = "#7aa2f7"

[colors.tab_bar.new_tab]
bg_color = "#1a1b26"
fg_color = "#7aa2f7"

[colors.tab_bar.new_tab_hover]
bg_color = "#1a1b26"
fg_color = "#7aa2f7"
intensity = "Bold"

[metadata]
aliases = []
author = "folke"
name = "myTheme"
